spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.108.128.11:3306/online_bookstore?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Mysql.666
server:
  port: 9090

# 去除控制台打印 swagger异常AbstractSerializableParameter（以下配置去掉不影响正常使用，但是控制台会报异常）
logging:
  level:
      io.swagger.models.parameters.AbstractSerializableParameter: error

#是否激活 swagger true or false
swagger:
  is:
    enable: true
